### PR TITLE
Fix for import error of MutableSequence in Python3.10.2

### PR DESCRIPTION
**Pull request by abhijitmamarde**
Its now moved to `collections.abc.MutableSequence`

### CODE REVIEW

**Comment by abhijitmamarde** [comment]
Checked in version 3.10.2 working fine now. Let me know if any more info is needed to merge this PR

**Comment by jesstucker** [comment]
@timwellswa

**Comment by techb0lt** [comment]
I just made the changes in this PR on my virtual environment and it sure works. It will be great if this PR can be merged please.

**Comment by timwellswa** [comment]
closing in favor of #174

**Pull request closed without merging**
