### PR TITLE
1.0.1 cleanup

### PR DESCRIPTION
**Pull request by claylo**
fix(version): use correct package version in User-Agent string

chore(tests): skip reports tests correctly when appropriate

docs(README): updates to Markdown and reStructured Text versions

### CODE REVIEW

**Comment by happybob007** [comment]
Clay,

The tests that require an Access Token (and that's probably going to be many of them) aren't likely to ever work in the CI framework -- since we don't want valid Access Tokens checked in.

Given that, I'm not sure there's much value in having Travis hooked up to automatically test code -- unless you can do that without needing to have the Access Token publicly available.

**Comment by kbrandl** [comment]
Thanks for the input, Scott.   The Access Token isn't actually in the SDK source code anywhere -- it's set via a config setting in Travis CI -- only users with Admin access to the Git repo can access the config settings in Travis CI, and the access token is obfuscated there, even for Admins who can access the settings.  So, I don't believe the Access Token is exposed anywhere (Clay has eveb redacted it in all debug output).  @claylo please feel free to chime in if I've mis-stated anything.

**Comment by kbrandl** [comment]
@claylo -- looks like the Travis CI build failed because it isn't picking up the Access Token from the Travis CI settings. Let's work through this offline in the morning.

**Comment by kbrandl** [comment]
(Closing this pull request -- will have Clay submit another once I've adjusted settings in Travis-CI.)

**Pull request closed without merging**
